#!/usr/bin/env bash

# ubuntu start scripts

VBoxManage startvm debpc &
xrdb < ~/.Xdefaults
if ps aux | grep gappproxy-1.0.0beta | grep -qv grep; then
	:
else
	$HOME/bin/gappproxy-1.0.0beta/localproxy/proxy.py
fi
if ! pidof urxvtd &> /dev/null; then
	urxvtd -q -o -f &
fi
