#!/usr/bin/env bash

# ubuntu start scripts

xrdb < ~/.Xdefaults
pkill urxvtd
sleep 2
urxvtd -q -o -f &

VBoxManage startvm debpc &

if ps aux | grep gappproxy-1.0.0beta | grep -qv grep; then
	:
else
	$HOME/bin/gappproxy-1.0.0beta/localproxy/proxy.py
fi
