font_family JetBrainsMono Nerd Font Mono
font_size 18.0

# 禁用普通左键点击直接打开链接
mouse_map left click ungrabbed

# 改成 Ctrl+左键打开链接
mouse_map ctrl+left release grabbed,ungrabbed mouse_handle_click link
mouse_map ctrl+left press grabbed discard_event

# 1) tab 放顶部
tab_bar_edge top

# 2) tab 标题加编号
tab_title_template "{index}. {title}"
active_tab_title_template "{index}. {title}"

# 3) Alt+数字切 tab，编号从 1 开始
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# foreground #ffffff
# background #000000
foreground            #e5e5e5
background            #000000
selection_foreground  #000000
selection_background  #e5e5e5
# Black
color0 #000000
color8 #4d4d4d

# Red
color1 #cd0000
color9 #ff0000

# Green
color2 #00cd00
color10 #00ff00

# Yellow
color3 #cdcd00
color11 #ffff00

# Blue
color4 #0000ee
color12 #5c5cff

# Magenta
color5 #cd00cd
color13 #ff00ff

# Cyan
color6 #00cdcd
color14 #00ffff

# White
color7 #e5e5e5
color15 #ffffff

tab_title_template "{title}"
active_tab_title_template "{title}"

scrollback_lines -1
scrollbar never

background_opacity 1.0
