---

- name: Create directories
  file: path=/etc/service/{{ name }}/log/main
        state=directory

- name: Log run file
  copy: src=log_run
        dest=/etc/service/{{ name }}/log/run
        mode=0755

- name: Run file
  template: src=run
            dest=/etc/service/{{ name }}/run
            mode=0755
  register: "runit_{{ name }}"
