---

- name: Enable the backports repository to install `docker.io`
  apt_repository: repo="deb http://http.debian.net/debian jessie-backports main" state=present

- name: Install packages
  apt: update_cache=yes name={{ item }} state=present
  with_items:
  - docker.io
  - python-docker
  tags: packages

- name: Run shadowsocks
  docker:
    image: menghan/shadowsocks
    detach: True
    name: "{{ item.name }}"
    ports: "{{ item.port }}:{{ item.port }}"
    publish_all_ports: yes
    state: started
    pull: always
    volumes: "{{ item.config }}:/etc/shadowsocks.json"
    restart_policy: always
  with_items: shadowsocks_instances
