---

- name: Enable the backports repository to install `docker.io`
  apt_repository: repo="deb http://http.debian.net/debian jessie-backports main" state=present
  tags: packages

- name: Install packages
  apt: update_cache=yes name={{ item }} state=present
  with_items:
  - docker.io
  - python-docker
  tags: packages

- name: Shadowsocks runner
  copy: src=runshadowsocks dest=/usr/local/bin/runshadowsocks mode=0755

- name: Run shadowsocks instances
  command: /usr/local/bin/runshadowsocks {{ item }}
  with_items: shadowsocks_instances
