#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/sky/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &

/home/sky/client/conky/src/conky &
/home/sky/bin/conkymsg &
if ! pidof urxvtd &> /dev/null; then
    urxvtd -q -o -f &
fi
if ! pidof mytunet &> /dev/null; then
	/etc/init.d/mytunetd start
fi
fbpanel &
xrdb < ~/.Xresource
pcmanx &
firefox &
urxvt -title proxy -e ssh ucenter -D 2008 &
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/sky/.fluxbox/log"
