#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/sky/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &

# xrandr --output VGA --auto --output LVDS --off
# xrandr --output LVDS --auto --rotate normal --pos 0x0 --panning 1366x768+0+132 --output VGA --auto --right-of LVDS
conky &
if ! pidof urxvtd &> /dev/null; then
    urxvtd -q -o -f &
fi
fbpanel &
xscreensaver -no-splash &
workrave &
xrdb < ~/.Xresource
# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/sky/.fluxbox/log"
