---

- name: Install prerequisites
  apt: update_cache=yes name={{ item }} state=present
  with_items:
  - apt-transport-https
  - python-pip
  - ca-certificates
  - linux-image-extra-virtual
  - python-setuptools

- name: Setup apt docker.list
  copy: src=docker.list dest=/etc/apt/sources.list.d
  register: init_docker

- name: Import docker repository key
  command: apt-key adv --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  when: init_docker.changed

- name: Remove obsolate package lxc-docker
  apt: name={{ item }} state=absent
  with_items:
  - lxc-docker

- name: Install package docker-engine
  apt: update_cache=yes name={{ item }} state=present
  with_items:
  - docker-engine

- name: Install required python packages
  pip: name={{ item }} state=present
  with_items:
  - docker-py
