---

- name: Setup apt source.list
  template: src=sources.list dest=/etc/apt/sources.list

- name: Install packages
  apt: update_cache=yes name={{ item }} state=present
  with_items:
  - lxc-docker
  - python-pip

- name: Install required python packages
  pip: name={{ item }} state=present
  with_items:
  - docker-py
