#!/usr/bin/env bash


backup ()
{
	if [ ! -e "$1" ]; then
		return
	fi
	path=$(dirname "$1")
	node=$(basename "$1")
	mv "$1" "$path"/"$node"-$(LANG=C date +%F-%H-%M-%S)
}

setup ()
{
	src=$1
	dst=$2

	if test -z $src -o -z $dst; then
		return
	fi
	backup $dst
	rm -rf $dst
	ln -s $src $dst
}

# install essential softwares..

sudo aptitude update
sudo aptitude install -y \
	git-core tig git-svn subversion \
	vim-gtk exuberant-ctags cscope tofrodos \
	build-essential manpages manpages-dev \
	lftp apache2 openssh-server openssh-client \
	postfix procmail mutt msmtp \
	evince poppler-data \
	ibus ibus-table-extraphrase ibus-table-wubi im-switch \
	ntfs-3g pcmanx-gtk2 rdesktop stardict \
	fluxbox fbpanel rxvt-unicode conky \
	ttf-dejavu ttf-dejavu-core ttf-dejavu-extra ttf-inconsolata \
	ttf-wqy-microhei ttf-droid \
	vim-doc git-doc \
	ipython python-examples python-doc \
	python3 python3-examples python3-doc \
	bash-completion unzip gawk less lsof screen sudo telnet wget curl \
	mailutils

# if with --new argument, it means bootstrap from the scratch
if [[ "$1" != "--new" ]]; then
	exit 0
fi

# get menghanrc
if [ -d $HOME/codespace/menghanrc ]; then
	backup $HOME/codespace/menghanrc
fi
echo 'please setup .ssh/config to make sure menghanrchost:.gitroot/menghanrc.git exists'
echo 'after done, press Enter to continue'
read
mkdir -p $HOME/codespace && cd $HOME/codespace && git clone menghanrchost:.gitroot/menghanrc.git
if ! test $?; then
	exit 1
fi

# setup bash env
cd
if ! grep -q '.bashrc.basic' ~/.bashrc; then
	echo "source ~/.bashrc.basic" >> ~/.bashrc
fi
if ! grep -q '.bashrc.aliases' ~/.bashrc; then
	echo "source ~/.bashrc.aliases" >> ~/.bashrc
fi
if ! grep -q '.bashrc.local' ~/.bashrc; then
	cat >> ~/.bashrc << EOF
if [ -f ~/.bashrc.local ]; then
	source ~/.bashrc.local
fi
EOF
fi
setup codespace/menghanrc/bashrcs/bashrc.basic .bashrc.basic
setup codespace/menghanrc/bashrcs/bashrc.aliases .bashrc.aliases

# setup bin/ scripts
cd
mkdir -p bin && cd bin
if test $?; then
	for f in $(ls ../codespace/menghanrc/scripts)
	do
		setup ../codespace/menghanrc/scripts/$f $f
	done
else
	echo 'Failed to cd "~/bin"'
fi

# setup vim env
cd
setup codespace/menghanrc/dot-vimrc .vimrc
setup codespace/menghanrc/dot-vimrcs .vimrcs
cd .vimrcs/plugins_src && ./install.sh

# setup git env
cd
setup codespace/menghanrc/dot-gitconfig .gitconfig

# setup screen env
cd
setup codespace/menghanrc/dot-screenrc .screenrc

# setup Xdefaults env
if grep -q 'Ubuntu' /etc/issue; then
	# ubuntu: don't use .Xdefaults
	:
else
	cd
	setup codespace/menghanrc/dot-Xdefaults .Xdefaults
fi

# setup python env
cd
setup codespace/menghanrc/dot-pythonstartup .pythonstartup

# setup fluxbox and fbpanel
cd
setup codespace/menghanrc/dot-fluxbox .fluxbox
setup codespace/menghanrc/dot-fbpanel .fbpanel
cd .fluxbox
cp -f init.example init

# setup mutt
cd
setup codespace/menghanrc/dot-mutt .mutt

# setup conky
cd
setup codespace/menghanrc/dot-conkys/dot-conkyrc .conkyrc

# setup toprc
cd
setup codespace/menghanrc/dot-toprc .toprc
