---

- hosts: devs
  roles:
  - install_packages
  tags: package

- hosts: devs
  roles:
  - setup_rc
  tags: rc

- hosts: dockers
  roles:
  - setup_docker
  tags: docker

- hosts: gbyte
  tasks:
  - name: start cow
    docker:
      image: menghan/cow
      state: reloaded
      command: "-rc /var/tmp/.cow/rc"
      expose:
      - 7777
      ports:
      - "7777:7777"
      volumes:
      - "/home/menghan/.cow/rc:/var/tmp/.cow/rc"
      pull: missing
      docker_api_version: 1.18
  tags: docker,cow

- hosts: shadowsockses
  roles:
  - { role: shadowsocks, mirror_country: us }
  tags: shadowsocks,proxy
